AWSTemplateFormatVersion: 2010-09-09
Description: Create a role to assume and a resource to have access to
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: jacobbucketbucket
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::268556604645:user/jjtest"
              #Service:
                #- s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: [
                  'arn:aws:s3:::*',
                  'arn:aws:s3:::jacobbucketbucket',
                  'arn:aws:s3:::jacobbucketbucket/*'

                ]
