#!/bin/bash

# Create VPC

VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region us-east-1 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=jacob-vpc}]' \
--query Vpc.VpcId \
--output text)

echo $VPC_ID

# Create IGW

IGW_ID=$(aws ec2 create-internet-gateway \
--tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=jacob-igw}]' \
--query InternetGateway.InternetGatewayId \
--output text)

echo $IGW_ID

# Attach IGW to VPC

aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Create subnets

SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block 172.1.0.0/24 \
--tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=jacob-subnet}]' \
--query Subnet.SubnetId \
--output text)

echo $SUBNET_ID

# Auto assign IPv4 addresses

aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch
# Associate subnets with route table

RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[].RouteTableId[]" \
--output text)

echo $RT_ID
aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID
# Add a route for route table to IGW

aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID
