#!/usr/bin/env bash

if [ -z "$1" ]; then
        echo "No bucket name provided"
        exit 1
fi

BUCKET_NAME=$1


aws s3 rm "s3://$BUCKET_NAME" --recursive

aws s3api delete-bucket --bucket $BUCKET_NAME
